### ISSUE TITLE
[OpenSource] Privacy and Analytics

### ISSUE THREAD

**Issue by IzzySoft** [Mercandj/file-android#2]
In the last version, you've introduced a bunch of trackers: Firebase Analytics, Crashlytics, GMS… Could you please revert that?

**Comment by Mercandj** [comment]
Hi,
Thks for the interest you have to this project. Like we discussed [here](https://github.com/Mercandj/browser/issues/8#issuecomment-435581909), Fabric crashlytics will be removed this year (if I remember correctly, this tool was bought by Google and will be replaced by Firebase). Regarding Firebase and Google services, I agree that it could be seen as trackers. But user data are anonymously sent. And open sources alternatives do not provide the same feature and same security/perfs...
Note: This app has been created to be distributed in the Google Play Store and is open source to let user be aware of what they install. That's why the trust about Google products is higher. File-android and my other apps contain dependencies: the only deps that are not open source are the one from Google. Knowing that, the choice is let to users to install this app or not.
Thanks again.

**Comment by IzzySoft** [comment]
Thanks for your fast answer, @Mercandj! I just see the version had no such stuff in 5 days ago. And us "tin foils" like it that way. The version from 5 days ago would even be eligible for F-Droid inclusion – but now unfortunately it's no longer.

Good to see you'll remove Crashlytics. But that still leaves Firebase Analytics (and in terms of F-Droid also GMS).

You speak of data being sent anonymously. While I would trust _you_ with that (even if not, I could check – after all, the code is open), how can you be sure about what those Google libraries do? They are not open source. You can never be sure what they do. And being integrated with your app, they have all the permissions your app has and can access the same data. So from a FOSS standpoint, I don't trust those libraries.

Thanks for the reference! Are you saying that Firebase is essential here now as well? It wasn't a few days ago :smile: 

Yes, of course it's the users' choice to install the app or not. Still it would be a pity having the choice restricted. I've dropped the update for now and disabled fetching updates for the app.

So again, thanks for considering! Of course it is your choice (as it is your app). Though as a privacy proponent, I'd very much welcome to see your app staying "clean" :wink:

PS: Should you decide otherwise, I'd suggest you change the app's title at Playstore – the current one could backfire: "File Manager FS 📂 Storage space - **No ads tracking"** is at least a bit misleading (unless you insert 3 letters: "No ads but tracking" or leave out the last word). Google Analytics (which is now Firebase Analytics) for most aware folks counts as tracking. Just a suggestion.

**Comment by Mercandj** [comment]
> I just see the version had no such stuff in 5 days ago.

I suppose that the versions you are talking are the one for Android TV (your remark is maybe due to your automatic checks based on release tags but your are wrong about that). The mobile app always needs Google services to work. (since [2014-2015](https://github.com/Mercandj/FileSpace-Android))

<img width="485" alt="screenshot 2019-01-27 at 00 07 45" src="https://user-images.githubusercontent.com/3717316/51793866-d2c75c80-21c7-11e9-876a-84f0e40b3d08.png">

> how can you be sure about what those Google libraries do

Indeed, I can't legally see what's inside non open source code (even if tools exist to do that). The only thing I can tell you is that the dashboard given to developers that are using Firebase gives data that are not intrusive to user privacy. (easy to confirm, Firebase is "free")

> You can never be sure what they do

Technically it's false, legally it's true but Terms of Services (ToS) are here to confirm. (If you don't read ToS or don't trust ToS it's another pb)

> Thanks for the reference! Are you saying that Firebase is essential here now as well? It wasn't a few days ago

It was a few day ago and was in the mobile app since more than 3 years (crash report, remote config, ab tests are very useful and drive development of new feature).

> So again, thanks for considering! Of course it is your choice (as it is your app). Though as a privacy proponent, I'd very much welcome to see your app staying "clean"

Yep, I understand

> I'd suggest you change the app's title

There is no tracking related to ads. I'm not expert of ToS, but I suppose that [Firebase ToS](https://firebase.google.com/terms/analytics/) are almost the same than the PlayStore one used to distribute the app. At least both Firebase and the way the app is distribute, are coming from the same society Google. The app is open source and does not collect Advertising Identifier and ToS of dependencies are not talking of that. So the title "No ads tracking" seems OK to me.

----

Thks again, I will close this issue as I consider that Google tools are not a privacy issue to user that have Google services on their phone. It's like don't trust Safari browser on an iPhone `^^`. (by the way, the play store and google services are both pre-installed apps that can track user with a lot of permissions already granted). This app is distribute to these users. My app only ask for storage permission (logic as it's a file manager). It's your right to don't trust Google, and if you don't trust Google please do not install this app on your device and more important: flash your phone with a ROM without play services!!! (Note: I even never try this app on an [AOSP](https://source.android.com/) ROM without play services installed, but I suppose that firebase will not work, no idea about that... If one day my app becomes pre-installed, I will remove all these Google dependencies).

**Comment by IzzySoft** [comment]
> I suppose that the versions you are talking are the one for Android TV

Comparing the sizes: seems you are right, yes.

> Terms of Services (ToS) are here to confirm.

Maybe, maybe not. I don't really trust Google if it comes to privacy. I know from cases where deleted backups were restored… So on the surface it might look correct (if no such lap happens). But you never know what data they really keep. They live on data.

> So the title "No ads tracking" seems OK to me.

I can follow your reasoning. But you know how it works: "That app claims no tracking and see, it comes with * Analytics". But yes, it was a suggestion only – up to you to decide, I just wanted to point out where potential trouble could be avoided. But maybe I'm seeing things that aren't there :wink:

> as I consider that Google tools are not a privacy issue to user that have Google services on their phone.

And what about those that haven't? I e.g. don't (but on my device, those Analytics would be blocked anyway). And from those who have them, noone explicitly wanted them: they come with the device if you want them or not. So saying "well, you've got GMS anyway" is a bit unfair.

> and more important: flash your phone with a ROM without play services!!!

No guess what :rofl: My devices are running LineageOS. Without GApps flashed.

Well, OK: Thanks again for your attention and for discussing this! Our standpoints seem to slightly differ (but I guess both of us can live with that). Please let me know once you've got a version with "less props" released, so I can check once more. And apologies for confusing the different builds!

**Comment by IzzySoft** [comment]
No pushing, just so it doesn't get missed: Please don't forget to let me know when I should check again :wink:
